# Generated by Django 4.2.5 on 2024-01-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0002_post_image_post_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('slider_title', models.CharField(blank=True, max_length=50, null=True)),
                ('slider_text', models.TextField()),
                ('poster_name', models.CharField(blank=True, max_length=50, null=True)),
                ('slider_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
