# Generated by Django 4.2.5 on 2024-02-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0003_home_hero_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_hero',
            name='poster_img',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
    ]
