# Generated by Django 4.2.5 on 2024-02-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0004_home_hero_poster_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('blog_title', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='politics_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('blog_title', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='science_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('blog_title', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='sports_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('blog_title', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='technology_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('blog_title', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
