# Generated by Django 4.2.5 on 2024-02-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0005_business_blog_politics_blog_science_blog_sports_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_blog',
            name='blog_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='politics_blog',
            name='blog_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='science_blog',
            name='blog_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sports_blog',
            name='blog_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='technology_blog',
            name='blog_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
