# Generated by Django 4.2.5 on 2024-02-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0008_blogcategory_business_blog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_blog',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_site.blogcategory'),
        ),
        migrations.AlterField(
            model_name='politics_blog',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_site.blogcategory'),
        ),
        migrations.AlterField(
            model_name='science_blog',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_site.blogcategory'),
        ),
        migrations.AlterField(
            model_name='sports_blog',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_site.blogcategory'),
        ),
        migrations.AlterField(
            model_name='technology_blog',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_site.blogcategory'),
        ),
    ]
