# Generated by Django 4.2.5 on 2024-02-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0011_alter_business_blog_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('blog_title', models.CharField(blank=True, max_length=150, null=True)),
                ('blog_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='politics_blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='science_blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sports_blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='technology_blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home_hero',
            name='slider_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BusinessBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog_site.blog')),
            ],
            bases=('blog_site.blog',),
        ),
        migrations.CreateModel(
            name='PoliticsBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog_site.blog')),
            ],
            bases=('blog_site.blog',),
        ),
        migrations.CreateModel(
            name='ScienceBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog_site.blog')),
            ],
            bases=('blog_site.blog',),
        ),
        migrations.CreateModel(
            name='SportsBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog_site.blog')),
            ],
            bases=('blog_site.blog',),
        ),
        migrations.CreateModel(
            name='TechnologyBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog_site.blog')),
            ],
            bases=('blog_site.blog',),
        ),
        migrations.DeleteModel(
            name='business_blog',
        ),
        migrations.DeleteModel(
            name='politics_blog',
        ),
        migrations.DeleteModel(
            name='science_blog',
        ),
        migrations.DeleteModel(
            name='sports_blog',
        ),
        migrations.DeleteModel(
            name='technology_blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_site.blogcategory'),
        ),
    ]
