# Generated by Django 4.2.5 on 2024-02-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0012_blog_remove_politics_blog_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='description',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
