# Generated by Django 4.2.5 on 2024-02-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0013_remove_blogcategory_description_blogcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='slug',
        ),
    ]
