# Generated by Django 4.2.5 on 2024-02-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0014_remove_blogcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
