# Generated by Django 4.2.5 on 2024-02-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0015_blogcategory_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='category_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
