# Generated by Django 4.2.5 on 2024-02-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0016_blogcategory_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='category_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
