# Generated by Django 4.2.1 on 2024-02-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0017_blogcategory_category_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurevideo',
            name='category',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_site.blogcategory'),
        ),
    ]
