# Generated by Django 4.2.1 on 2024-02-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0019_featurevideocategory_alter_featurevideo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurevideocategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
