# Generated by Django 4.2.5 on 2024-02-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0020_alter_featurevideocategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('story', models.TextField()),
                ('about_img', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('ourStory', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
